[package]
name = "cron"
version = "0.0.1"
authors = ["@bufrsh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
